version: '3'

services:
  web:
    build: .
    expose:
      - "8000"
    volumes:
      - .:/app
    environment:
      - POSTGRES_DB=doc_manager
      - POSTGRES_USER=doc_manager
      - POSTGRES_PASSWORD=grYhCT6Y4oo85lSu
    command: >
      sh -c "sleep 30 &&
             python manage.py migrate &&
             python manage.py collectstatic --noinput &&
             gunicorn --bind 0.0.0.0:8000 doc_manager.wsgi:application"
    networks:
      - doc_manager

  db:
    image: postgres:alpine
    environment:
      - POSTGRES_DB=doc_manager
      - POSTGRES_USER=doc_manager
      - POSTGRES_PASSWORD=grYhCT6Y4oo85lSu
    networks:
      - doc_manager

  nginx:
    image: nginx:alpine
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./static:/static
      - ./media:/media
    ports:
      - "80:80"
    depends_on:
      - web
    networks:
      - doc_manager

networks:
  doc_manager:
