# Generated by Django 5.0.4 on 2024-04-30 18:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RequestDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256, verbose_name='Назва Заявки')),
                ('price', models.FloatField(verbose_name='Ціна [UAH]')),
                ('date_conclusion', models.DateField(blank=True, null=True, verbose_name='Дата складання договору')),
                ('date_payment', models.DateField(blank=True, null=True, verbose_name='Дата оплати')),
            ],
            options={
                'verbose_name': 'Заявка',
                'verbose_name_plural': 'Заяви',
            },
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64, verbose_name='Назва')),
                ('it_end', models.BooleanField(verbose_name='Це закрита угода?')),
            ],
            options={
                'verbose_name': 'Статус заявки',
                'verbose_name_plural': 'Статуси заявки',
            },
        ),
        migrations.CreateModel(
            name='RequestEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=256, verbose_name='Автор')),
                ('title', models.CharField(max_length=256, verbose_name='Назва події')),
                ('detail', models.TextField(verbose_name='Опис події')),
                ('created_at', models.DateTimeField(auto_now=True, verbose_name='Створено')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event', to='control.requestdocument', verbose_name='Заявка')),
                ('new_status', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='new_status', to='control.status', verbose_name='Статус після зміни')),
                ('old_status', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='old_status', to='control.status', verbose_name='Статус до зміни')),
            ],
            options={
                'verbose_name': 'Заявка',
                'verbose_name_plural': 'Заяви',
            },
        ),
        migrations.AddField(
            model_name='requestdocument',
            name='status',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='control.status', verbose_name='Статус'),
        ),
    ]
