# Generated by Django 5.0.4 on 2024-04-30 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='requestevent',
            options={'verbose_name': 'Подія завявки', 'verbose_name_plural': 'Події заявок'},
        ),
        migrations.AlterModelOptions(
            name='status',
            options={'verbose_name': 'Статус заявки', 'verbose_name_plural': 'Статуси заявок'},
        ),
        migrations.AddField(
            model_name='requestdocument',
            name='document',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='Файл документу'),
        ),
    ]
