# Generated by Django 5.0.4 on 2024-04-30 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0002_alter_requestevent_options_alter_status_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestdocument',
            name='created_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Створено'),
        ),
    ]
